routes/web.php
<?php

use App\Http\Controllers\HelloController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\BrandController;
use App\Http\Controllers\MultipicController;
use Illuminate\Support\Facades\Route;
use App\Models\User;
use Illuminate\Support\Facades\DB;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/admin', function () {
    return view('backend.home');
});

Route::get('/', function () {
    return view('welcome');
});

Route::get('/hello', function(){
    echo "Hello!";
})->middleware('checkage');
//Route::get('/hello', [HelloController::class, 'index'])->middleware('checkage');

Route::get('/hello1', [HelloController::class, 'index']);

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    //$users = User::all();
    $users = DB::table('users')
            ->select('name','email','created_at')->get();
    return view('dashboard', compact('users'));
})->name('dashboard');


//Category
Route::resource('category', CategoryController::class)->middleware('auth:sanctum');
//Soft Delete
Route::get('softdelete/category/{id}', [CategoryController::class, 'SoftDelete']);

Route::get('/category/restore/{id}', [CategoryController::class, 'Restore']);
Route::get('/pdelete/category/{id}', [CategoryController::class, 'Pdelete']);


//Brand
Route::resource('brand', BrandController::class);
Route::get('/brand/delete/{id}', [BrandController::class, 'Delete']);


// Multi Image
Route::resource('multipic', MultipicController::class);


//

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use SoftDeletes;
    protected $fillable = [
        'user_id',
        'category_name'
    ];

    public function user(){
        return $this->hasOne(User::class, 'id', 'user_id');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Category;
use Illuminate\Support\Facades\Auth;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;

class CategoryController extends Controller
{
    public function __construct(){
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $categories = DB::table('categories')
        //         ->join('users','categories.user_id','users.id')
        //         ->select('categories.*','users.name')
        //         ->latest()->paginate(5);


        $categories = Category::latest()->paginate(5);
        $trachCat = Category::onlyTrashed()->latest()->paginate(3);

       // $categories = DB::table('categories')->latest()->paginate(5);
       return view('backend.category.index', compact('categories','trachCat'));
       //return view('category.index', compact('categories'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'category_name' => 'required|unique:categories|max:255',

        ],
        [
            'category_name.required' => 'Please Input Category Name',
            'category_name.max' => 'Category Less Then 255Chars',
        ]);

        Category::insert([
            'category_name' => $request->category_name,
            'user_id' => Auth::user()->id,
            'created_at' => Carbon::now()
        ]);

        // $category = new Category;
        // $category->category_name = $request->category_name;
        // $category->user_id = Auth::user()->id;
        // $category->save();

        // $data = array();
        // $data['category_name'] = $request->category_name;
        // $data['user_id'] = Auth::user()->id;
        // DB::table('categories')->insert($data);

        return Redirect()->back()->with('success','Category Inserted Successfull');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //$categories = Category::find($id);
        //$categories = Category::findOrFail($id);
        //$categories = DB::table('categories')->where('id', $id)->first();
        //dd($categories); die();

        $categories = DB::table('categories')->where('id',$id)->first();
        return view('backend.category.edit',compact('categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) //Category $cat
    {
        //dd($cat);die();
        // $update = Category::findOrfail($id)->update([
        //     'category_name' => $request->category_name,
        //     'user_id'       => Auth::user()->id
        // ]);
        // $update = Category::find($id)->update([
        //     'category_name' => $request->category_name,
        //     'user_id'       => Auth::user()->id
        // ]);
        //$update = Category::findOrFail($id);
        // $update = Category::find($id);
        // $update->category_name = $request->category_name;
        // $update->user_id       = Auth::user()->id;
        // $update->update();
        // dd($update);die();

        $data = array();
        $data['category_name'] = $request->category_name;
        $data['user_id']       = Auth::user()->id;
        DB::table('categories')->where('id', $id)->update($data);

        return Redirect()->route('backend.category.index')->with('success', 'Category Updated Successful...');
    }

    //Soft Delete
    public function SoftDelete($id){
        $delete = Category::find($id)->delete();
        return Redirect()->back()->with('success','Category Soft Delete Successfully');
    }

    public function Restore($id){
        $delete = Category::withTrashed()->find($id)->restore();
        return Redirect()->back()->with('success','Category Restore Successfully');

    }

   public function Pdelete($id){
       $delete = Category::onlyTrashed()->find($id)->forceDelete();
       return Redirect()->back()->with('success','Category Permanently Deleted');
   }



    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/backend/category/edit.blade.php
@extends('backend.layouts.app')

@section('content')


    <div class="py-12">
        <div class="container">
            <div class="row">




                <div class="col-md-8">
                    <div class="card">
                        <div class="card-header"> Edit Category </div>
                        <div class="card-body">



                        <form action="{{ URL::to('category/'.$categories->id)  }}" method="POST">
                            @csrf {{ method_field('put') }}
                            <div class="form-group">
                                <label for="exampleInputEmail1">Update Category Name</label>
                                <input type="text" name="category_name" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" value="{{ $categories->category_name }}">

                                    @error('category_name')
                                        <span class="text-danger"> {{ $message }}</span>
                                    @enderror

                            </div>

                            <button type="submit" class="btn btn-primary">Update Category</button>
                        </form>

                        </div>

                    </div>
                </div>



            </div>
        </div>

    </div>

@endsection

resources/views/backend/category/index.blade.php
@extends('backend.layouts.app')

@section('content')


    <div class="py-12">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    @if(session('success'))
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            <strong>{{ session('success') }}</strong>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    @endif
                    <div class="card">
                        <div class="card-hrader"></div>
                        <table class="table">
                            <thead>
                              <tr>
                                <th scope="col">SL No</th>
                                <th scope="col">Category Name</th>
                                <th scope="col">User</th>
                                <th scope="col">Created At</th>
                                <th scope="col">Action</th>
                              </tr>
                            </thead>
                            <tbody>
                                <!-- @php($i = 1) -->
                                @foreach($categories as $category)
                                    <tr>
                                    <th scope="row"> {{ $categories->firstItem()+$loop->index  }} </th>
                                    <td> {{ $category->category_name }} </td>
                                    {{-- <td> {{ $category->name }} </td> --}}
                                    <td> {{ $category->user->name }} </td>
                                    <td>
                                        @if($category->created_at ==  NULL)
                                        <span class="text-danger"> No Date Set</span>
                                        @else
                                    {{ Carbon\Carbon::parse($category->created_at)->diffForHumans() }}
                                        @endif
                                        </td>
                                        <td>
                                            <a href="{{ url('category/'.$category->id.'/edit') }}" class="btn btn-info">Edit</a>
                                            <a href="{{ url('softdelete/category', $category->id) }}" class="btn btn-danger">Delete</a>
                                        </td>


                                    </tr>
                                @endforeach

                              </tbody>
                        </table>
                        {{ $categories->links() }}
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-hrader">Add Category</div><hr>
                        <div class="card-body">
                            <form action="{{ route('category.store') }}" method="POST">
                                @csrf
                                <div class="form-group">
                                <label for="exampleInputEmail1">Category Name</label>
                                <input type="text" name="category_name" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">

                                        @error('category_name')
                                            <span class="text-danger"> {{ $message }}</span>
                                        @enderror

                                </div>

                                <button type="submit" class="btn btn-primary">Add Category</button>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>



    </div>



     <!-- Trash Part -->

  <div class="container">
    <div class="row">


    <div class="col-md-8">
     <div class="card">




        <div class="card-header">Trash List </div>


            <table class="table">
                <thead>
                    <tr>
                    <th scope="col">SL No</th>
                    <th scope="col">Category Name</th>
                    <th scope="col">User</th>
                    <th scope="col">Created At</th>
                    <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                        <!-- @php($i = 1) -->
                        @foreach($trachCat as $category)
                    <tr>
                    <th scope="row"> {{ $categories->firstItem()+$loop->index  }} </th>
                    <td> {{ $category->category_name }} </td>
                    <td> {{ $category->user->name }} </td>
                    <td>
                        @if($category->created_at ==  NULL)
                        <span class="text-danger"> No Date Set</span>
                        @else
                    {{ Carbon\Carbon::parse($category->created_at)->diffForHumans() }}
                        @endif
                    </td>
                    <td>
                    <a href="{{ url('category/restore/'.$category->id) }}" class="btn btn-info">Restore</a>
                    <a href="{{ url('pdelete/category/'.$category->id) }}" class="btn btn-danger">P Delete</a>
                        </td>


                    </tr>
                    @endforeach


                </tbody>
            </table>
             {{ $trachCat->links() }}

        </div>
     </div>


        <div class="col-md-4"></div>



    </div>
  </div>

   <!-- End Trush -->

@endsection