routes/web.php
<?php

use App\Http\Controllers\HelloController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\BrandController;
use App\Http\Controllers\MultipicController;
use Illuminate\Support\Facades\Route;
use App\Models\User;
use Illuminate\Support\Facades\DB;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/admin', function () {
    return view('backend.home');
});

Route::get('/', function () {
    return view('welcome');
});

Route::get('/hello', function(){
    echo "Hello!";
})->middleware('checkage');
//Route::get('/hello', [HelloController::class, 'index'])->middleware('checkage');

Route::get('/hello1', [HelloController::class, 'index']);

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    //$users = User::all();
    $users = DB::table('users')
            ->select('name','email','created_at')->get();
    return view('dashboard', compact('users'));
})->name('dashboard');


//Category
Route::resource('category', CategoryController::class)->middleware('auth:sanctum');
//Soft Delete
Route::get('softdelete/category/{id}', [CategoryController::class, 'SoftDelete']);

Route::get('/category/restore/{id}', [CategoryController::class, 'Restore']);
Route::get('/pdelete/category/{id}', [CategoryController::class, 'Pdelete']);


//Brand
Route::resource('brand', BrandController::class);
Route::get('/brand/delete/{id}', [BrandController::class, 'Delete']);


// Multi Image
Route::resource('multipic', MultipicController::class);


//

app/Models/Brand.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Brand extends Model
{
    use HasFactory;
    protected $fillable = [
        'brand_name',
        'brand_image',

    ];
}

app/Http/Controllers/BrandController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Brand;
use App\Models\Multipic;
use Illuminate\Support\Carbon;
use Image;
use Auth;


class BrandController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $brands = Brand::latest()->paginate(5);
        return view('backend.brand.index' , compact('brands'));
    }

    public function store(Request $request){

        $validatedData = $request->validate([
            'brand_name' => 'required|unique:brands|min:4',
            'brand_image' => 'required|mimes:jpg.jpeg,png',

        ],
        [
            'brand_name.required' => 'Please Input Brand Name',
            'brand_image.min' => 'Brand Longer then 4 Characters',
        ]);

        $brand_image =  $request->file('brand_image');

        // $name_gen = hexdec(uniqid());
        // $img_ext = strtolower($brand_image->getClientOriginalExtension());
        // $img_name = $name_gen.'.'.$img_ext;
        // $up_location = 'image/brand/';
        // $last_img = $up_location.$img_name;
        // $brand_image->move($up_location,$img_name);

        $name_gen = hexdec(uniqid()).'.'.$brand_image->getClientOriginalExtension();
        Image::make($brand_image)->resize(300,200)->save('image/brand/'.$name_gen);

        $last_img = 'image/brand/'.$name_gen;

        Brand::insert([
            'brand_name' => $request->brand_name,
            'brand_image' => $last_img,
            'created_at' => Carbon::now()
        ]);

        $notification = array(
            'message' => 'Brand Inserted Successfully',
            'alert-type' => 'success'
        );

        return Redirect()->back()->with('success', 'Brand Insert Successful');
    }

    public function edit($id)
    {
        $brands = Brand::find($id);
        return view('backend.brand.edit',compact('brands'));
    }

    public function update(Request $request, $id) {
        $validatedData = $request->validate([
            'brand_name' => 'required|min:4',

        ],
        [
            'brand_name.required' => 'Please Input Brand Name',
            'brand_image.min' => 'Brand Longer then 4 Characters',
        ]);

        $old_image = $request->old_image;

        $brand_image =  $request->file('brand_image');

        if($brand_image){

        $name_gen = hexdec(uniqid());
        $img_ext = strtolower($brand_image->getClientOriginalExtension());
        $img_name = $name_gen.'.'.$img_ext;
        $up_location = 'image/brand/';
        $last_img = $up_location.$img_name;
        $brand_image->move($up_location,$img_name);

        unlink($old_image);
        Brand::find($id)->update([
            'brand_name' => $request->brand_name,
            'brand_image' => $last_img,
            'created_at' => Carbon::now()
        ]);

        $notification = array(
            'message' => 'Brand Updated Successfully',
            'alert-type' => 'info'
        );
        return Redirect()->route('brand.index')->with('success', 'Brand Update Successful...');

        }else{
            Brand::find($id)->update([
                'brand_name' => $request->brand_name,
                'created_at' => Carbon::now()
            ]);
            $notification = array(
                'message' => 'Brand Updated Successfully',
                'alert-type' => 'warning'
            );

            return Redirect()->route('backend.brand.index')->with('success', 'Brand Updated Successfully');

        }
    }


    public function Delete($id){
        $image = Brand::find($id);
        $old_image = $image->brand_image;
        unlink($old_image);

       Brand::find($id)->delete();
       $notification = array(
           'message' => 'Brand Delete Successfully',
           'alert-type' => 'error'
       );
       return Redirect()->route('backend.brand.index')->with('success', 'Brand Delete Successfully');

    }

}

resources/views/backend/brand/edit.blade.php
@extends('backend.layouts.app')

@section('content')


    <div class="py-12">
        <div class="container">
            <div class="row">

                <div class="col-md-8">
                    @if(session('success'))
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        <strong>{{ session('success') }}</strong>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    @endif
                    <div class="card">
                        <div class="card-header"> Edit Brand </div>
                        <div class="card-body">



                            <form action="{{ url('brand/'.$brands->id)  }}" method="POST" enctype="multipart/form-data">
                                @csrf{{ method_field('put') }}
                                <input type="hidden" name="old_image" value="{{ $brands->brand_image }}">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Update Brand Name</label>
                                    <input type="text" name="brand_name" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" value="{{ $brands->brand_name }}">

                                        @error('brand_name')
                                            <span class="text-danger"> {{ $message }}</span>
                                        @enderror

                                </div>


                                <div class="form-group">
                                    <label for="exampleInputEmail1">Update Brand Image</label>
                                    <input type="file" name="brand_image" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" value="{{ $brands->brand_image }}">

                                        @error('brand_image')
                                            <span class="text-danger"> {{ $message }}</span>
                                        @enderror

                                </div>


                                    <div class="form-group">
                                    <img src="{{ asset($brands->brand_image) }}" style="width:400px; height:200px;" >

                                    </div>



                                <button type="submit" class="btn btn-primary">Update Brand</button>
                            </form>

                        </div>

                    </div>
                </div>



            </div>
        </div>

    </div>

@endsection

resources/views/backend/brand/index.blade.php
@extends('backend.layouts.app')

@section('content')


    <div class="py-12">
        <div class="container">
            <div class="row">


                <div class="col-md-8">
                    @if(session('success'))
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            <strong>{{ session('success') }}</strong>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    @endif
                <div class="card">

                        <table class="table">
                            <thead>
                                <tr>
                                <th scope="col">SL No</th>
                                <th scope="col">Brand Name</th>
                                <th scope="col">Brand Image</th>
                                <th scope="col">Created At</th>
                                <th scope="col">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                    <!-- @php($i = 1) -->
                                    @foreach($brands as $brand)
                                <tr>
                                <th scope="row"> {{ $brands->firstItem()+$loop->index  }} </th>
                                <td> {{ $brand->brand_name }} </td>
                                <td> <img src="{{ asset($brand->brand_image) }}" style="height:40px; width:70px;" > </td>
                                <td>
                                    @if($brand->created_at ==  NULL)
                                    <span class="text-danger"> No Date Set</span>
                                    @else
                                {{ Carbon\Carbon::parse($brand->created_at)->diffForHumans() }}
                                    @endif
                                </td>
                                <td>
                                <a href="{{ url('brand/'.$brand->id.'/edit') }}" class="btn btn-info">Edit</a>
                                <a href="{{ url('/brand/delete',$brand->id) }}" onclick="return confirm('Are you sure to delete')" class="btn btn-danger">Delete</a>
                                </td>


                                </tr>
                                @endforeach


                            </tbody>
                        </table>
                    {{ $brands->links() }}

                </div>
                </div>


                <div class="col-md-4">
                    <div class="card">
                        <div class="card-header"> Add Brand </div>
                        <div class="card-body">



                            <form action="{{ route('brand.store') }}" method="POST" enctype="multipart/form-data">
                                @csrf
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Brand Name</label>
                                    <input type="text" name="brand_name" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">

                                        @error('brand_name')
                                            <span class="text-danger"> {{ $message }}</span>
                                        @enderror

                                </div>


                                <div class="form-group">
                                    <label for="exampleInputEmail1">Brand Image</label>
                                    <input type="file" name="brand_image" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">

                                        @error('brand_image')
                                            <span class="text-danger"> {{ $message }}</span>
                                        @enderror

                                </div>




                                <button type="submit" class="btn btn-primary">Add Brand</button>
                            </form>

                        </div>

                    </div>
                </div>

            </div>
        </div>

    </div>


@endsection