routes/web.php
<?php

use App\Http\Controllers\HelloController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\BrandController;
use App\Http\Controllers\MultipicController;
use Illuminate\Support\Facades\Route;
use App\Models\User;
use Illuminate\Support\Facades\DB;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/admin', function () {
    return view('backend.home');
});

Route::get('/', function () {
    return view('welcome');
});

Route::get('/hello', function(){
    echo "Hello!";
})->middleware('checkage');
//Route::get('/hello', [HelloController::class, 'index'])->middleware('checkage');

Route::get('/hello1', [HelloController::class, 'index']);

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    //$users = User::all();
    $users = DB::table('users')
            ->select('name','email','created_at')->get();
    return view('dashboard', compact('users'));
})->name('dashboard');


//Category
Route::resource('category', CategoryController::class)->middleware('auth:sanctum');
//Soft Delete
Route::get('softdelete/category/{id}', [CategoryController::class, 'SoftDelete']);

Route::get('/category/restore/{id}', [CategoryController::class, 'Restore']);
Route::get('/pdelete/category/{id}', [CategoryController::class, 'Pdelete']);


//Brand
Route::resource('brand', BrandController::class);
Route::get('/brand/delete/{id}', [BrandController::class, 'Delete']);


// Multi Image
Route::resource('multipic', MultipicController::class);


//

app/Models/Multipic.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Multipic extends Model
{
    use HasFactory;
}

app/Http/Controllers/MultipicController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Multipic;
use Image;
use Illuminate\Support\Carbon;

class MultipicController extends Controller
{
    public function __construct(){
        $this->middleware('auth');
    }


    public function index(){
        $images = Multipic::all();
        return view('backend.multipic.index',compact('images'));
    }


    public function store(Request $request){

       $image =  $request->file('image');

       foreach($image as $multi_img){

       $name_gen = hexdec(uniqid()).'.'.$multi_img->getClientOriginalExtension();
       Image::make($multi_img)->resize(300,300)->save('image/multi/'.$name_gen);

       $last_img = 'image/multi/'.$name_gen;

       Multipic::insert([

           'image' => $last_img,
           'created_at' => Carbon::now()
       ]);
           } // end of the foreach



        return Redirect()->back()->with('success','Multi Image Inserted Successfully');


    }
}

resources/views/backend/multipic/index.blade.php
@extends('backend.layouts.app')

@section('content')

    <div class="py-12">
        <div class="container">
            <div class="row">


                <div class="col-md-8">
                    <div class="card-group">
                        @foreach($images as $multi)
                        <div class="col-md-4 mt-5">
                            <div class="card">
                            <img src="{{ asset($multi->image) }}" alt="">

                            </div>

                        </div>
                        @endforeach

                    </div>


                </div>


                <div class="col-md-4">
                    <div class="card">
                        <div class="card-header"> Multi Image </div>
                            <div class="card-body">

                            <form action="{{ route('multipic.store') }}" method="POST" enctype="multipart/form-data">
                                @csrf
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Multi Image</label>
                                    <input type="file" name="image[]" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" multiple="">

                                        @error('image')
                                            <span class="text-danger"> {{ $message }}</span>
                                        @enderror

                                </div>
                                <button type="submit" class="btn btn-primary">Add Image</button>
                            </form>

                        </div>

                    </div>
                </div>



            </div>
        </div>

    </div>


@endsection